#!/usr/bin/make
# makefile for cap-rel laravel projects
#

SHELL = bash
MODULE = uptosign

.DEFAULT_GOAL := help

help:
	@echo 'Available commands:'
	@echo -e 'prod \t\t — \t build app'
	@echo -e 'dev \t\t — \t build app in dev mode (js not compressed)'
	@echo -e 'zip \t\t — \t build zip file'


prod:

zip: prod
	(php ./build/buildzip.php)

dev:
	rsync -avP . root@192.168.16.183:/var/www/dolibarr-18/htdocs/custom/${MODULE}
