#!/usr/bin/make
# makefile for cap-rel laravel projects
#

SHELL = bash
MODULE = uptosign

DOC_HOST     ?= doc.cap-rel.fr
DOC_PATH     ?= /home/webs/doc.cap-rel.fr/marginaliamd/data/documents/$(MODULE)

MARGINALIAMD ?= $(HOME)/dev/marginaliamd

.DEFAULT_GOAL := help
.PHONY: help zip deploy-doc screenshots

help:
	@echo 'Available commands:'
	@echo -e 'prod \t\t — \t build app'
	@echo -e 'dev \t\t — \t build app in dev mode (js not compressed)'
	@echo -e 'zip \t\t — \t build zip file'
	@echo -e '  deploy-doc   \t — \t publish user documentation to doc.cap-rel.fr'
	@echo -e '  screenshots  \t — \t collect missing screenshots interactively'


prod:

zip: prod
	(php ./build/buildzip.php)

deploy-doc:
	rsync -avLP docs/users/ $(DOC_HOST):$(DOC_PATH)/

screenshots:
	php $(MARGINALIAMD)/cli/collect-screenshots.php docs/users/

dev:
	rsync -avP . root@192.168.16.183:/var/www/dolibarr-18/htdocs/custom/${MODULE}
